name: "Apply Stack after PR is Merged"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  terraform:
    name: "Terraform Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        # You may pin to the exact commit or the version.
        # uses: little-core-labs/install-terraform@1e577535d279f1999a5abf60337ddc3ff225e79d
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          # Version of terraform to download
          version: 1.7.5

      - name: Run apply
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: |
          terraform init
          terraform apply -auto-approve -input=false

      - name: Commit state
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action #mandatory for the output to show up in ${{ steps }}
        with:
          commit_message: Save terraform state
